### ISSUE TITLE
support split terminal window

### ISSUE THREAD

**Issue by zuoRambo** [JetBrains/jediterm#143]
the terminal embed in IDE(PHPStorm,PyCharm,Webstorm etc.) is nice but not perfect.

It will be better if it could support split terminal window by the follow way "split horizontally" and "split vertically" .

Look forward to your reply.

**Comment by IonutBajescu** [comment]
You could do that with tmux although at the moment there are a few issues with running it inside an intelij editor such as PHPStorm:

![image](https://cloud.githubusercontent.com/assets/5365516/25662403/46e4b252-300c-11e7-8f48-9fb2523f4446.png)

**Comment by truginis** [comment]
so this is not happening?

**Comment by traff** [comment]
Hi, it is already implemented in IntelliJ platform and will be available in 2018.3 product line.

**Comment by mrself** [comment]
@traff Can you please make it clear how to use splitting functionality in 2018.3? I have it installed but I do not see any new options in settings/

**Comment by scoobster17** [comment]
Just had a play with this and it seems that you have to drag the console tab in the editor to the area that has been split, after moving to editor. Whilst being a pain, this also means that they are always visible, unless manually moved.

What would be great is if we could have split tabs in the terminal 'drawer(?)' so that it can be hidden/expanded with a keyboard shortcut, as terminal already is, but persist it's own layout. Just instead of displaying as tabs, it would allow the same configurability in terms of vertical/horizontal splitting as the editor.
