### ISSUE TITLE
Connect a java.lang.Process instance to JediTermWidget

### ISSUE THREAD

**Issue by omegaui** [JetBrains/jediterm#238]
Hi!

Is it possible to connect a `java.lang.Process` instance to `JediTermWidget`?

like a `PtyProcess` can be connected to `JediTermWidget` as below,

```java
process = PtyProcess.exec(command, envs, directory);
widget.setTtyConnector(new PtyProcessTtyConnector(process, Charset.forName("UTF-8")));
```

I took a look at `ProcessTtyConnector` but it is abstract and needs the following methods to be implemented

```java
public class MyProcessTtyConnector extends ProcessTtyConnector{
	
	@Override
	public String getName(){
		//What should be the returned value
		return "";
	}
	
	@Override
	public boolean isConnected(){
		//How to know if the process is still connected
		return process.isAlive(); // Like this or ...
	}
	
	@Override
	public void resizeImmediately(){
		//What's this for?
	}
}
```

How can I implement it to achieve so?

**Comment by omegaui** [comment]
@segrey

**Comment by segrey** [comment]
@omegaui 1. `getName()` returns a tab title, it's going to be deprecated in future releases; you can return an empty string here.
2. `isConnected()` - yes, return simply `process.isAlive()`. Thanks, I've added a default implementation for `ProcessTtyConnector.isConnected`.
3. `resizeImmediately()` is deprecated; you don't need to implement it. An empty default implementation should work.

**Comment by omegaui** [comment]
Thanks!!

I'll check this, if this works then

I will close this issue.

**Comment by omegaui** [comment]
It is working but,
the caret and the lines on the terminal is getting placed unevenly like this
```ignorelang
line1 is here
                                  line2 is here
                                                                 line3 is here
                                                                                             and the caret is here
```

They all have whitespaces at start point.

I think this repo should have a tested non-abstract `ProcessTtyConnector`.

**Comment by segrey** [comment]
@omegaui The problem is that processes started via `Runtime.exec` have `\n` in their output streams for line endings. Even it looks as expected, however, when processed by a terminal emulator, "new line" character just moves the cursor on the next line, whereas "carriage return" moves the cursor to the beginning of the line. So, actually, you need to emit `\r\n` if you want to move cursor to the beginning of the next line. Why does it work for PTY processes? Because PTY converts `\n` to `\r\n` by default. If you're on Unix, you'll see `onlcr` in `stty -a` output in a terminal. If it's disabled, there will be a similar indentation in the output:
```
[~]$ echo 'foo\nbar'
foo
bar
[~]$ stty -onlcr
[~]$ echo 'foo\nbar'
foo
   bar
```

Either output `\r\n` as new lines explicitly, or start `PtyProcess` using [pty4j](https://github.com/JetBrains/pty4j) library - see [com.jediterm.app.JediTerm#createTtyConnector](https://github.com/JetBrains/jediterm/blob/071eee8e3510539b4730d4f2b2513aacda5066e0/JediTerm/src/main/kotlin/com/jediterm/app/JediTermMain.kt#L71) as an example.
