### ISSUE TITLE
Set the TERMINAL_EMULATOR environment variable

### ISSUE THREAD

**Issue by mikehearn** [JetBrains/jediterm#253]
Sometimes console libraries need to detect the IntelliJ terminal to work around quirks or customize things in other ways. Today there's no good way to do this. It would be ideal if TERMINAL_EMULATOR were to be set in the environment of the shell consistently, so apps can know what they're dealing with.

**Comment by ajalt** [comment]
[VSCode][1] and [XTerm/iTerm][2] all use the environment variable `TERM_PROGRAM`, so that seems to be the most standard.

[1]: https://code.visualstudio.com/docs/terminal/shell-integration
[2]: https://stackoverflow.com/questions/7052683/how-can-i-identify-the-current-terminal-emulator-from-a-bash-script/7053241#7053241

**Comment by segrey** [comment]
Actually, IntelliJ terminal sets `TERMINAL_EMULATOR=JetBrains-JediTerm` environment variable in [IntelliJ terminal plugin](https://github.com/JetBrains/intellij-community/blob/master/plugins/terminal/src/org/jetbrains/plugins/terminal/LocalTerminalDirectRunner.java#L141).
