### ISSUE TITLE
Solve split packages problem for running JediTerm on JPMS

### ISSUE THREAD

**Issue by PavelTurk** [JetBrains/jediterm#280]
I've just discovered that both jars - `core` and `ui` have split packages, for example `com.jediterm.terminal` what makes it impossible to use them on JPMS. 

I suggest to rename all packages in `core` so that ALL of them start with `com.jediterm.core`, for example `com.jediterm.core.terminal`. And ALL packages in `ui` will start with `com.jediterm.ui`, for example, `com.jediterm.ui.terminal`.

I can try to do it, if I get confirmation on this issue.

**Comment by segrey** [comment]
@PavelTurk I'm sorry for the long delay, I didn't mean to be rude. Please accept my sincere apologies.

>However, it should be done through deprecation of classes in com.jediterm.terminal, because of their current usages by IntelliJ external plugins.

Well, the problem here is that jediterm-core.jar and jediterm-ui.jar are leaked to public API for IntelliJ external plugins. So, if we just move packages to new location, these external plugins will be broken once the next IntelliJ IDE is released with updated jediterm-core.jar / jediterm-ui.jar.

For example, `com.jediterm.terminal.model.TerminalTextBuffer` has 87 external usages by 10 external plugins.

<img width="1840" alt="image" src="https://github.com/JetBrains/jediterm/assets/607109/0fcf1bef-ba74-407c-9bc0-6ddae0f3cab2">

So, we need to have deprecate old classes and retain them for a while.
